//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceForms
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://ics.lu.se/")]
    public partial class Customer : object
    {
        
        private string NameField;
        
        private int CustomerIDField;
        
        private string UserNameField;
        
        private string AddressField;
        
        private int PhoneNumberField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://ics.lu.se/")]
    public partial class Product : object
    {
        
        private int ProductIDField;
        
        private string ProductNameField;
        
        private decimal PriceField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://ics.lu.se/")]
    public partial class Store : object
    {
        
        private int SupermarketIDField;
        
        private string RegionNameField;
        
        private string StoreNameField;
        
        private string CityField;
        
        private string StoreAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupermarketID
        {
            get
            {
                return this.SupermarketIDField;
            }
            set
            {
                this.SupermarketIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StoreName
        {
            get
            {
                return this.StoreNameField;
            }
            set
            {
                this.StoreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StoreAddress
        {
            get
            {
                return this.StoreAddressField;
            }
            set
            {
                this.StoreAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategory", Namespace="http://ics.lu.se/")]
    public partial class ProductCategory : object
    {
        
        private int CategoryIDField;
        
        private string CategoryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://ics.lu.se/")]
    public partial class Order : object
    {
        
        private int OrderIDField;
        
        private string OrderDateField;
        
        private int SupermarketIDField;
        
        private int CustomerIDField;
        
        private string PaymentMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SupermarketID
        {
            get
            {
                return this.SupermarketIDField;
            }
            set
            {
                this.SupermarketIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ics.lu.se/", ConfigurationName="ServiceReferenceForms.WebService1Soap")]
    public interface WebService1Soap
    {
        
        // CODEGEN: Generating message contract since element name GetCustomersResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCustomers", ReplyAction="*")]
        ServiceReferenceForms.GetCustomersResponse GetCustomers(ServiceReferenceForms.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetCustomersResponse> GetCustomersAsync(ServiceReferenceForms.GetCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductsResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProducts", ReplyAction="*")]
        ServiceReferenceForms.GetProductsResponse GetProducts(ServiceReferenceForms.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetProductsResponse> GetProductsAsync(ServiceReferenceForms.GetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetStoresResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetStores", ReplyAction="*")]
        ServiceReferenceForms.GetStoresResponse GetStores(ServiceReferenceForms.GetStoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetStores", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetStoresResponse> GetStoresAsync(ServiceReferenceForms.GetStoresRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoriesResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCategories", ReplyAction="*")]
        ServiceReferenceForms.GetCategoriesResponse GetCategories(ServiceReferenceForms.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetCategoriesResponse> GetCategoriesAsync(ServiceReferenceForms.GetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrdersResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrders", ReplyAction="*")]
        ServiceReferenceForms.GetOrdersResponse GetOrders(ServiceReferenceForms.GetOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetOrdersResponse> GetOrdersAsync(ServiceReferenceForms.GetOrdersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomers", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetCustomersRequestBody Body;
        
        public GetCustomersRequest()
        {
        }
        
        public GetCustomersRequest(ServiceReferenceForms.GetCustomersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomersRequestBody
    {
        
        public GetCustomersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetCustomersResponseBody Body;
        
        public GetCustomersResponse()
        {
        }
        
        public GetCustomersResponse(ServiceReferenceForms.GetCustomersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetCustomersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceForms.Customer> GetCustomersResult;
        
        public GetCustomersResponseBody()
        {
        }
        
        public GetCustomersResponseBody(System.Collections.Generic.List<ServiceReferenceForms.Customer> GetCustomersResult)
        {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetProductsRequestBody Body;
        
        public GetProductsRequest()
        {
        }
        
        public GetProductsRequest(ServiceReferenceForms.GetProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody
    {
        
        public GetProductsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetProductsResponseBody Body;
        
        public GetProductsResponse()
        {
        }
        
        public GetProductsResponse(ServiceReferenceForms.GetProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceForms.Product> GetProductsResult;
        
        public GetProductsResponseBody()
        {
        }
        
        public GetProductsResponseBody(System.Collections.Generic.List<ServiceReferenceForms.Product> GetProductsResult)
        {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoresRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStores", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetStoresRequestBody Body;
        
        public GetStoresRequest()
        {
        }
        
        public GetStoresRequest(ServiceReferenceForms.GetStoresRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStoresRequestBody
    {
        
        public GetStoresRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStoresResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetStoresResponseBody Body;
        
        public GetStoresResponse()
        {
        }
        
        public GetStoresResponse(ServiceReferenceForms.GetStoresResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetStoresResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceForms.Store> GetStoresResult;
        
        public GetStoresResponseBody()
        {
        }
        
        public GetStoresResponseBody(System.Collections.Generic.List<ServiceReferenceForms.Store> GetStoresResult)
        {
            this.GetStoresResult = GetStoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategories", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetCategoriesRequestBody Body;
        
        public GetCategoriesRequest()
        {
        }
        
        public GetCategoriesRequest(ServiceReferenceForms.GetCategoriesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoriesRequestBody
    {
        
        public GetCategoriesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetCategoriesResponseBody Body;
        
        public GetCategoriesResponse()
        {
        }
        
        public GetCategoriesResponse(ServiceReferenceForms.GetCategoriesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetCategoriesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceForms.ProductCategory> GetCategoriesResult;
        
        public GetCategoriesResponseBody()
        {
        }
        
        public GetCategoriesResponseBody(System.Collections.Generic.List<ServiceReferenceForms.ProductCategory> GetCategoriesResult)
        {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrders", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetOrdersRequestBody Body;
        
        public GetOrdersRequest()
        {
        }
        
        public GetOrdersRequest(ServiceReferenceForms.GetOrdersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOrdersRequestBody
    {
        
        public GetOrdersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceForms.GetOrdersResponseBody Body;
        
        public GetOrdersResponse()
        {
        }
        
        public GetOrdersResponse(ServiceReferenceForms.GetOrdersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetOrdersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceForms.Order> GetOrdersResult;
        
        public GetOrdersResponseBody()
        {
        }
        
        public GetOrdersResponseBody(System.Collections.Generic.List<ServiceReferenceForms.Order> GetOrdersResult)
        {
            this.GetOrdersResult = GetOrdersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebService1SoapChannel : ServiceReferenceForms.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceReferenceForms.WebService1Soap>, ServiceReferenceForms.WebService1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceForms.GetCustomersResponse ServiceReferenceForms.WebService1Soap.GetCustomers(ServiceReferenceForms.GetCustomersRequest request)
        {
            return base.Channel.GetCustomers(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceForms.Customer> GetCustomers()
        {
            ServiceReferenceForms.GetCustomersRequest inValue = new ServiceReferenceForms.GetCustomersRequest();
            inValue.Body = new ServiceReferenceForms.GetCustomersRequestBody();
            ServiceReferenceForms.GetCustomersResponse retVal = ((ServiceReferenceForms.WebService1Soap)(this)).GetCustomers(inValue);
            return retVal.Body.GetCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetCustomersResponse> ServiceReferenceForms.WebService1Soap.GetCustomersAsync(ServiceReferenceForms.GetCustomersRequest request)
        {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceForms.GetCustomersResponse> GetCustomersAsync()
        {
            ServiceReferenceForms.GetCustomersRequest inValue = new ServiceReferenceForms.GetCustomersRequest();
            inValue.Body = new ServiceReferenceForms.GetCustomersRequestBody();
            return ((ServiceReferenceForms.WebService1Soap)(this)).GetCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceForms.GetProductsResponse ServiceReferenceForms.WebService1Soap.GetProducts(ServiceReferenceForms.GetProductsRequest request)
        {
            return base.Channel.GetProducts(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceForms.Product> GetProducts()
        {
            ServiceReferenceForms.GetProductsRequest inValue = new ServiceReferenceForms.GetProductsRequest();
            inValue.Body = new ServiceReferenceForms.GetProductsRequestBody();
            ServiceReferenceForms.GetProductsResponse retVal = ((ServiceReferenceForms.WebService1Soap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetProductsResponse> ServiceReferenceForms.WebService1Soap.GetProductsAsync(ServiceReferenceForms.GetProductsRequest request)
        {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceForms.GetProductsResponse> GetProductsAsync()
        {
            ServiceReferenceForms.GetProductsRequest inValue = new ServiceReferenceForms.GetProductsRequest();
            inValue.Body = new ServiceReferenceForms.GetProductsRequestBody();
            return ((ServiceReferenceForms.WebService1Soap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceForms.GetStoresResponse ServiceReferenceForms.WebService1Soap.GetStores(ServiceReferenceForms.GetStoresRequest request)
        {
            return base.Channel.GetStores(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceForms.Store> GetStores()
        {
            ServiceReferenceForms.GetStoresRequest inValue = new ServiceReferenceForms.GetStoresRequest();
            inValue.Body = new ServiceReferenceForms.GetStoresRequestBody();
            ServiceReferenceForms.GetStoresResponse retVal = ((ServiceReferenceForms.WebService1Soap)(this)).GetStores(inValue);
            return retVal.Body.GetStoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetStoresResponse> ServiceReferenceForms.WebService1Soap.GetStoresAsync(ServiceReferenceForms.GetStoresRequest request)
        {
            return base.Channel.GetStoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceForms.GetStoresResponse> GetStoresAsync()
        {
            ServiceReferenceForms.GetStoresRequest inValue = new ServiceReferenceForms.GetStoresRequest();
            inValue.Body = new ServiceReferenceForms.GetStoresRequestBody();
            return ((ServiceReferenceForms.WebService1Soap)(this)).GetStoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceForms.GetCategoriesResponse ServiceReferenceForms.WebService1Soap.GetCategories(ServiceReferenceForms.GetCategoriesRequest request)
        {
            return base.Channel.GetCategories(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceForms.ProductCategory> GetCategories()
        {
            ServiceReferenceForms.GetCategoriesRequest inValue = new ServiceReferenceForms.GetCategoriesRequest();
            inValue.Body = new ServiceReferenceForms.GetCategoriesRequestBody();
            ServiceReferenceForms.GetCategoriesResponse retVal = ((ServiceReferenceForms.WebService1Soap)(this)).GetCategories(inValue);
            return retVal.Body.GetCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetCategoriesResponse> ServiceReferenceForms.WebService1Soap.GetCategoriesAsync(ServiceReferenceForms.GetCategoriesRequest request)
        {
            return base.Channel.GetCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceForms.GetCategoriesResponse> GetCategoriesAsync()
        {
            ServiceReferenceForms.GetCategoriesRequest inValue = new ServiceReferenceForms.GetCategoriesRequest();
            inValue.Body = new ServiceReferenceForms.GetCategoriesRequestBody();
            return ((ServiceReferenceForms.WebService1Soap)(this)).GetCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceForms.GetOrdersResponse ServiceReferenceForms.WebService1Soap.GetOrders(ServiceReferenceForms.GetOrdersRequest request)
        {
            return base.Channel.GetOrders(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceForms.Order> GetOrders()
        {
            ServiceReferenceForms.GetOrdersRequest inValue = new ServiceReferenceForms.GetOrdersRequest();
            inValue.Body = new ServiceReferenceForms.GetOrdersRequestBody();
            ServiceReferenceForms.GetOrdersResponse retVal = ((ServiceReferenceForms.WebService1Soap)(this)).GetOrders(inValue);
            return retVal.Body.GetOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceForms.GetOrdersResponse> ServiceReferenceForms.WebService1Soap.GetOrdersAsync(ServiceReferenceForms.GetOrdersRequest request)
        {
            return base.Channel.GetOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceForms.GetOrdersResponse> GetOrdersAsync()
        {
            ServiceReferenceForms.GetOrdersRequest inValue = new ServiceReferenceForms.GetOrdersRequest();
            inValue.Body = new ServiceReferenceForms.GetOrdersRequestBody();
            return ((ServiceReferenceForms.WebService1Soap)(this)).GetOrdersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/WebServiceClient1/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/WebServiceClient1/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
