//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceClient1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://ics.lu.se/")]
    public partial class Customer : object
    {
        
        private string NameField;
        
        private int CustomerIDField;
        
        private string UserNameField;
        
        private string AddressField;
        
        private int PhoneNumberField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://ics.lu.se/")]
    public partial class Product : object
    {
        
        private int ProductIDField;
        
        private string ProductNameField;
        
        private decimal PriceField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://ics.lu.se/")]
    public partial class Store : object
    {
        
        private int SupermarketIDField;
        
        private string RegionNameField;
        
        private string StoreNameField;
        
        private string CityField;
        
        private string StoreAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupermarketID
        {
            get
            {
                return this.SupermarketIDField;
            }
            set
            {
                this.SupermarketIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StoreName
        {
            get
            {
                return this.StoreNameField;
            }
            set
            {
                this.StoreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StoreAddress
        {
            get
            {
                return this.StoreAddressField;
            }
            set
            {
                this.StoreAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategory", Namespace="http://ics.lu.se/")]
    public partial class ProductCategory : object
    {
        
        private int CategoryIDField;
        
        private string CategoryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://ics.lu.se/")]
    public partial class Order : object
    {
        
        private int OrderIDField;
        
        private string OrderDateField;
        
        private int SupermarketIDField;
        
        private int CustomerIDField;
        
        private string PaymentMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SupermarketID
        {
            get
            {
                return this.SupermarketIDField;
            }
            set
            {
                this.SupermarketIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orderline", Namespace="http://ics.lu.se/")]
    public partial class Orderline : object
    {
        
        private int OrderIDField;
        
        private int ProductIDField;
        
        private int OrderlineNumberField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OrderlineNumber
        {
            get
            {
                return this.OrderlineNumberField;
            }
            set
            {
                this.OrderlineNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ics.lu.se/", ConfigurationName="ServiceReferenceClient1.WebService1Soap")]
    public interface WebService1Soap
    {
        
        // CODEGEN: Generating message contract since element name GetCustomersResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCustomers", ReplyAction="*")]
        ServiceReferenceClient1.GetCustomersResponse GetCustomers(ServiceReferenceClient1.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetCustomersResponse> GetCustomersAsync(ServiceReferenceClient1.GetCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductsResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProducts", ReplyAction="*")]
        ServiceReferenceClient1.GetProductsResponse GetProducts(ServiceReferenceClient1.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductsResponse> GetProductsAsync(ServiceReferenceClient1.GetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetStoresResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetStores", ReplyAction="*")]
        ServiceReferenceClient1.GetStoresResponse GetStores(ServiceReferenceClient1.GetStoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetStores", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetStoresResponse> GetStoresAsync(ServiceReferenceClient1.GetStoresRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoriesResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCategories", ReplyAction="*")]
        ServiceReferenceClient1.GetCategoriesResponse GetCategories(ServiceReferenceClient1.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetCategoriesResponse> GetCategoriesAsync(ServiceReferenceClient1.GetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrdersResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrders", ReplyAction="*")]
        ServiceReferenceClient1.GetOrdersResponse GetOrders(ServiceReferenceClient1.GetOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrdersResponse> GetOrdersAsync(ServiceReferenceClient1.GetOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductsFromCategoryResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProductsFromCategory", ReplyAction="*")]
        ServiceReferenceClient1.GetProductsFromCategoryResponse GetProductsFromCategory(ServiceReferenceClient1.GetProductsFromCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProductsFromCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductsFromCategoryResponse> GetProductsFromCategoryAsync(ServiceReferenceClient1.GetProductsFromCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetCustomerByIDResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCustomerByID", ReplyAction="*")]
        ServiceReferenceClient1.GetCustomerByIDResponse GetCustomerByID(ServiceReferenceClient1.GetCustomerByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetCustomerByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetCustomerByIDResponse> GetCustomerByIDAsync(ServiceReferenceClient1.GetCustomerByIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductPriceHighestResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProductPriceHighest", ReplyAction="*")]
        ServiceReferenceClient1.GetProductPriceHighestResponse GetProductPriceHighest(ServiceReferenceClient1.GetProductPriceHighestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetProductPriceHighest", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductPriceHighestResponse> GetProductPriceHighestAsync(ServiceReferenceClient1.GetProductPriceHighestRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrdersFromCustomerResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrdersFromCustomer", ReplyAction="*")]
        ServiceReferenceClient1.GetOrdersFromCustomerResponse GetOrdersFromCustomer(ServiceReferenceClient1.GetOrdersFromCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrdersFromCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrdersFromCustomerResponse> GetOrdersFromCustomerAsync(ServiceReferenceClient1.GetOrdersFromCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrderLinesFromOrderResult from namespace http://ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrderLinesFromOrder", ReplyAction="*")]
        ServiceReferenceClient1.GetOrderLinesFromOrderResponse GetOrderLinesFromOrder(ServiceReferenceClient1.GetOrderLinesFromOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/GetOrderLinesFromOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrderLinesFromOrderResponse> GetOrderLinesFromOrderAsync(ServiceReferenceClient1.GetOrderLinesFromOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomers", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetCustomersRequestBody Body;
        
        public GetCustomersRequest()
        {
        }
        
        public GetCustomersRequest(ServiceReferenceClient1.GetCustomersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomersRequestBody
    {
        
        public GetCustomersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetCustomersResponseBody Body;
        
        public GetCustomersResponse()
        {
        }
        
        public GetCustomersResponse(ServiceReferenceClient1.GetCustomersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetCustomersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.Customer> GetCustomersResult;
        
        public GetCustomersResponseBody()
        {
        }
        
        public GetCustomersResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.Customer> GetCustomersResult)
        {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetProductsRequestBody Body;
        
        public GetProductsRequest()
        {
        }
        
        public GetProductsRequest(ServiceReferenceClient1.GetProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody
    {
        
        public GetProductsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetProductsResponseBody Body;
        
        public GetProductsResponse()
        {
        }
        
        public GetProductsResponse(ServiceReferenceClient1.GetProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.Product> GetProductsResult;
        
        public GetProductsResponseBody()
        {
        }
        
        public GetProductsResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.Product> GetProductsResult)
        {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoresRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStores", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetStoresRequestBody Body;
        
        public GetStoresRequest()
        {
        }
        
        public GetStoresRequest(ServiceReferenceClient1.GetStoresRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStoresRequestBody
    {
        
        public GetStoresRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStoresResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetStoresResponseBody Body;
        
        public GetStoresResponse()
        {
        }
        
        public GetStoresResponse(ServiceReferenceClient1.GetStoresResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetStoresResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.Store> GetStoresResult;
        
        public GetStoresResponseBody()
        {
        }
        
        public GetStoresResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.Store> GetStoresResult)
        {
            this.GetStoresResult = GetStoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategories", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetCategoriesRequestBody Body;
        
        public GetCategoriesRequest()
        {
        }
        
        public GetCategoriesRequest(ServiceReferenceClient1.GetCategoriesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoriesRequestBody
    {
        
        public GetCategoriesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetCategoriesResponseBody Body;
        
        public GetCategoriesResponse()
        {
        }
        
        public GetCategoriesResponse(ServiceReferenceClient1.GetCategoriesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetCategoriesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.ProductCategory> GetCategoriesResult;
        
        public GetCategoriesResponseBody()
        {
        }
        
        public GetCategoriesResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.ProductCategory> GetCategoriesResult)
        {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrders", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetOrdersRequestBody Body;
        
        public GetOrdersRequest()
        {
        }
        
        public GetOrdersRequest(ServiceReferenceClient1.GetOrdersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOrdersRequestBody
    {
        
        public GetOrdersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetOrdersResponseBody Body;
        
        public GetOrdersResponse()
        {
        }
        
        public GetOrdersResponse(ServiceReferenceClient1.GetOrdersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetOrdersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.Order> GetOrdersResult;
        
        public GetOrdersResponseBody()
        {
        }
        
        public GetOrdersResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.Order> GetOrdersResult)
        {
            this.GetOrdersResult = GetOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsFromCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsFromCategory", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetProductsFromCategoryRequestBody Body;
        
        public GetProductsFromCategoryRequest()
        {
        }
        
        public GetProductsFromCategoryRequest(ServiceReferenceClient1.GetProductsFromCategoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetProductsFromCategoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int categoryID;
        
        public GetProductsFromCategoryRequestBody()
        {
        }
        
        public GetProductsFromCategoryRequestBody(int categoryID)
        {
            this.categoryID = categoryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsFromCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsFromCategoryResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetProductsFromCategoryResponseBody Body;
        
        public GetProductsFromCategoryResponse()
        {
        }
        
        public GetProductsFromCategoryResponse(ServiceReferenceClient1.GetProductsFromCategoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetProductsFromCategoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.Product> GetProductsFromCategoryResult;
        
        public GetProductsFromCategoryResponseBody()
        {
        }
        
        public GetProductsFromCategoryResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.Product> GetProductsFromCategoryResult)
        {
            this.GetProductsFromCategoryResult = GetProductsFromCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByID", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetCustomerByIDRequestBody Body;
        
        public GetCustomerByIDRequest()
        {
        }
        
        public GetCustomerByIDRequest(ServiceReferenceClient1.GetCustomerByIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetCustomerByIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public GetCustomerByIDRequestBody()
        {
        }
        
        public GetCustomerByIDRequestBody(int customerID)
        {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByIDResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetCustomerByIDResponseBody Body;
        
        public GetCustomerByIDResponse()
        {
        }
        
        public GetCustomerByIDResponse(ServiceReferenceClient1.GetCustomerByIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetCustomerByIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceClient1.Customer GetCustomerByIDResult;
        
        public GetCustomerByIDResponseBody()
        {
        }
        
        public GetCustomerByIDResponseBody(ServiceReferenceClient1.Customer GetCustomerByIDResult)
        {
            this.GetCustomerByIDResult = GetCustomerByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductPriceHighestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductPriceHighest", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetProductPriceHighestRequestBody Body;
        
        public GetProductPriceHighestRequest()
        {
        }
        
        public GetProductPriceHighestRequest(ServiceReferenceClient1.GetProductPriceHighestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductPriceHighestRequestBody
    {
        
        public GetProductPriceHighestRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductPriceHighestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductPriceHighestResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetProductPriceHighestResponseBody Body;
        
        public GetProductPriceHighestResponse()
        {
        }
        
        public GetProductPriceHighestResponse(ServiceReferenceClient1.GetProductPriceHighestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetProductPriceHighestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceClient1.Product GetProductPriceHighestResult;
        
        public GetProductPriceHighestResponseBody()
        {
        }
        
        public GetProductPriceHighestResponseBody(ServiceReferenceClient1.Product GetProductPriceHighestResult)
        {
            this.GetProductPriceHighestResult = GetProductPriceHighestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersFromCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersFromCustomer", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetOrdersFromCustomerRequestBody Body;
        
        public GetOrdersFromCustomerRequest()
        {
        }
        
        public GetOrdersFromCustomerRequest(ServiceReferenceClient1.GetOrdersFromCustomerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetOrdersFromCustomerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public GetOrdersFromCustomerRequestBody()
        {
        }
        
        public GetOrdersFromCustomerRequestBody(int customerID)
        {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersFromCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersFromCustomerResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetOrdersFromCustomerResponseBody Body;
        
        public GetOrdersFromCustomerResponse()
        {
        }
        
        public GetOrdersFromCustomerResponse(ServiceReferenceClient1.GetOrdersFromCustomerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetOrdersFromCustomerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.Order> GetOrdersFromCustomerResult;
        
        public GetOrdersFromCustomerResponseBody()
        {
        }
        
        public GetOrdersFromCustomerResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.Order> GetOrdersFromCustomerResult)
        {
            this.GetOrdersFromCustomerResult = GetOrdersFromCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderLinesFromOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderLinesFromOrder", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetOrderLinesFromOrderRequestBody Body;
        
        public GetOrderLinesFromOrderRequest()
        {
        }
        
        public GetOrderLinesFromOrderRequest(ServiceReferenceClient1.GetOrderLinesFromOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetOrderLinesFromOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OrderID;
        
        public GetOrderLinesFromOrderRequestBody()
        {
        }
        
        public GetOrderLinesFromOrderRequestBody(int OrderID)
        {
            this.OrderID = OrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderLinesFromOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderLinesFromOrderResponse", Namespace="http://ics.lu.se/", Order=0)]
        public ServiceReferenceClient1.GetOrderLinesFromOrderResponseBody Body;
        
        public GetOrderLinesFromOrderResponse()
        {
        }
        
        public GetOrderLinesFromOrderResponse(ServiceReferenceClient1.GetOrderLinesFromOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se/")]
    public partial class GetOrderLinesFromOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceClient1.Orderline> GetOrderLinesFromOrderResult;
        
        public GetOrderLinesFromOrderResponseBody()
        {
        }
        
        public GetOrderLinesFromOrderResponseBody(System.Collections.Generic.List<ServiceReferenceClient1.Orderline> GetOrderLinesFromOrderResult)
        {
            this.GetOrderLinesFromOrderResult = GetOrderLinesFromOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebService1SoapChannel : ServiceReferenceClient1.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceReferenceClient1.WebService1Soap>, ServiceReferenceClient1.WebService1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetCustomersResponse ServiceReferenceClient1.WebService1Soap.GetCustomers(ServiceReferenceClient1.GetCustomersRequest request)
        {
            return base.Channel.GetCustomers(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.Customer> GetCustomers()
        {
            ServiceReferenceClient1.GetCustomersRequest inValue = new ServiceReferenceClient1.GetCustomersRequest();
            inValue.Body = new ServiceReferenceClient1.GetCustomersRequestBody();
            ServiceReferenceClient1.GetCustomersResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetCustomers(inValue);
            return retVal.Body.GetCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetCustomersResponse> ServiceReferenceClient1.WebService1Soap.GetCustomersAsync(ServiceReferenceClient1.GetCustomersRequest request)
        {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetCustomersResponse> GetCustomersAsync()
        {
            ServiceReferenceClient1.GetCustomersRequest inValue = new ServiceReferenceClient1.GetCustomersRequest();
            inValue.Body = new ServiceReferenceClient1.GetCustomersRequestBody();
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetProductsResponse ServiceReferenceClient1.WebService1Soap.GetProducts(ServiceReferenceClient1.GetProductsRequest request)
        {
            return base.Channel.GetProducts(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.Product> GetProducts()
        {
            ServiceReferenceClient1.GetProductsRequest inValue = new ServiceReferenceClient1.GetProductsRequest();
            inValue.Body = new ServiceReferenceClient1.GetProductsRequestBody();
            ServiceReferenceClient1.GetProductsResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductsResponse> ServiceReferenceClient1.WebService1Soap.GetProductsAsync(ServiceReferenceClient1.GetProductsRequest request)
        {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductsResponse> GetProductsAsync()
        {
            ServiceReferenceClient1.GetProductsRequest inValue = new ServiceReferenceClient1.GetProductsRequest();
            inValue.Body = new ServiceReferenceClient1.GetProductsRequestBody();
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetStoresResponse ServiceReferenceClient1.WebService1Soap.GetStores(ServiceReferenceClient1.GetStoresRequest request)
        {
            return base.Channel.GetStores(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.Store> GetStores()
        {
            ServiceReferenceClient1.GetStoresRequest inValue = new ServiceReferenceClient1.GetStoresRequest();
            inValue.Body = new ServiceReferenceClient1.GetStoresRequestBody();
            ServiceReferenceClient1.GetStoresResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetStores(inValue);
            return retVal.Body.GetStoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetStoresResponse> ServiceReferenceClient1.WebService1Soap.GetStoresAsync(ServiceReferenceClient1.GetStoresRequest request)
        {
            return base.Channel.GetStoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetStoresResponse> GetStoresAsync()
        {
            ServiceReferenceClient1.GetStoresRequest inValue = new ServiceReferenceClient1.GetStoresRequest();
            inValue.Body = new ServiceReferenceClient1.GetStoresRequestBody();
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetStoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetCategoriesResponse ServiceReferenceClient1.WebService1Soap.GetCategories(ServiceReferenceClient1.GetCategoriesRequest request)
        {
            return base.Channel.GetCategories(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.ProductCategory> GetCategories()
        {
            ServiceReferenceClient1.GetCategoriesRequest inValue = new ServiceReferenceClient1.GetCategoriesRequest();
            inValue.Body = new ServiceReferenceClient1.GetCategoriesRequestBody();
            ServiceReferenceClient1.GetCategoriesResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetCategories(inValue);
            return retVal.Body.GetCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetCategoriesResponse> ServiceReferenceClient1.WebService1Soap.GetCategoriesAsync(ServiceReferenceClient1.GetCategoriesRequest request)
        {
            return base.Channel.GetCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetCategoriesResponse> GetCategoriesAsync()
        {
            ServiceReferenceClient1.GetCategoriesRequest inValue = new ServiceReferenceClient1.GetCategoriesRequest();
            inValue.Body = new ServiceReferenceClient1.GetCategoriesRequestBody();
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetOrdersResponse ServiceReferenceClient1.WebService1Soap.GetOrders(ServiceReferenceClient1.GetOrdersRequest request)
        {
            return base.Channel.GetOrders(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.Order> GetOrders()
        {
            ServiceReferenceClient1.GetOrdersRequest inValue = new ServiceReferenceClient1.GetOrdersRequest();
            inValue.Body = new ServiceReferenceClient1.GetOrdersRequestBody();
            ServiceReferenceClient1.GetOrdersResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetOrders(inValue);
            return retVal.Body.GetOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrdersResponse> ServiceReferenceClient1.WebService1Soap.GetOrdersAsync(ServiceReferenceClient1.GetOrdersRequest request)
        {
            return base.Channel.GetOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrdersResponse> GetOrdersAsync()
        {
            ServiceReferenceClient1.GetOrdersRequest inValue = new ServiceReferenceClient1.GetOrdersRequest();
            inValue.Body = new ServiceReferenceClient1.GetOrdersRequestBody();
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetProductsFromCategoryResponse ServiceReferenceClient1.WebService1Soap.GetProductsFromCategory(ServiceReferenceClient1.GetProductsFromCategoryRequest request)
        {
            return base.Channel.GetProductsFromCategory(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.Product> GetProductsFromCategory(int categoryID)
        {
            ServiceReferenceClient1.GetProductsFromCategoryRequest inValue = new ServiceReferenceClient1.GetProductsFromCategoryRequest();
            inValue.Body = new ServiceReferenceClient1.GetProductsFromCategoryRequestBody();
            inValue.Body.categoryID = categoryID;
            ServiceReferenceClient1.GetProductsFromCategoryResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetProductsFromCategory(inValue);
            return retVal.Body.GetProductsFromCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductsFromCategoryResponse> ServiceReferenceClient1.WebService1Soap.GetProductsFromCategoryAsync(ServiceReferenceClient1.GetProductsFromCategoryRequest request)
        {
            return base.Channel.GetProductsFromCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductsFromCategoryResponse> GetProductsFromCategoryAsync(int categoryID)
        {
            ServiceReferenceClient1.GetProductsFromCategoryRequest inValue = new ServiceReferenceClient1.GetProductsFromCategoryRequest();
            inValue.Body = new ServiceReferenceClient1.GetProductsFromCategoryRequestBody();
            inValue.Body.categoryID = categoryID;
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetProductsFromCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetCustomerByIDResponse ServiceReferenceClient1.WebService1Soap.GetCustomerByID(ServiceReferenceClient1.GetCustomerByIDRequest request)
        {
            return base.Channel.GetCustomerByID(request);
        }
        
        public ServiceReferenceClient1.Customer GetCustomerByID(int customerID)
        {
            ServiceReferenceClient1.GetCustomerByIDRequest inValue = new ServiceReferenceClient1.GetCustomerByIDRequest();
            inValue.Body = new ServiceReferenceClient1.GetCustomerByIDRequestBody();
            inValue.Body.customerID = customerID;
            ServiceReferenceClient1.GetCustomerByIDResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetCustomerByID(inValue);
            return retVal.Body.GetCustomerByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetCustomerByIDResponse> ServiceReferenceClient1.WebService1Soap.GetCustomerByIDAsync(ServiceReferenceClient1.GetCustomerByIDRequest request)
        {
            return base.Channel.GetCustomerByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetCustomerByIDResponse> GetCustomerByIDAsync(int customerID)
        {
            ServiceReferenceClient1.GetCustomerByIDRequest inValue = new ServiceReferenceClient1.GetCustomerByIDRequest();
            inValue.Body = new ServiceReferenceClient1.GetCustomerByIDRequestBody();
            inValue.Body.customerID = customerID;
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetCustomerByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetProductPriceHighestResponse ServiceReferenceClient1.WebService1Soap.GetProductPriceHighest(ServiceReferenceClient1.GetProductPriceHighestRequest request)
        {
            return base.Channel.GetProductPriceHighest(request);
        }
        
        public ServiceReferenceClient1.Product GetProductPriceHighest()
        {
            ServiceReferenceClient1.GetProductPriceHighestRequest inValue = new ServiceReferenceClient1.GetProductPriceHighestRequest();
            inValue.Body = new ServiceReferenceClient1.GetProductPriceHighestRequestBody();
            ServiceReferenceClient1.GetProductPriceHighestResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetProductPriceHighest(inValue);
            return retVal.Body.GetProductPriceHighestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductPriceHighestResponse> ServiceReferenceClient1.WebService1Soap.GetProductPriceHighestAsync(ServiceReferenceClient1.GetProductPriceHighestRequest request)
        {
            return base.Channel.GetProductPriceHighestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetProductPriceHighestResponse> GetProductPriceHighestAsync()
        {
            ServiceReferenceClient1.GetProductPriceHighestRequest inValue = new ServiceReferenceClient1.GetProductPriceHighestRequest();
            inValue.Body = new ServiceReferenceClient1.GetProductPriceHighestRequestBody();
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetProductPriceHighestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetOrdersFromCustomerResponse ServiceReferenceClient1.WebService1Soap.GetOrdersFromCustomer(ServiceReferenceClient1.GetOrdersFromCustomerRequest request)
        {
            return base.Channel.GetOrdersFromCustomer(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.Order> GetOrdersFromCustomer(int customerID)
        {
            ServiceReferenceClient1.GetOrdersFromCustomerRequest inValue = new ServiceReferenceClient1.GetOrdersFromCustomerRequest();
            inValue.Body = new ServiceReferenceClient1.GetOrdersFromCustomerRequestBody();
            inValue.Body.customerID = customerID;
            ServiceReferenceClient1.GetOrdersFromCustomerResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetOrdersFromCustomer(inValue);
            return retVal.Body.GetOrdersFromCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrdersFromCustomerResponse> ServiceReferenceClient1.WebService1Soap.GetOrdersFromCustomerAsync(ServiceReferenceClient1.GetOrdersFromCustomerRequest request)
        {
            return base.Channel.GetOrdersFromCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrdersFromCustomerResponse> GetOrdersFromCustomerAsync(int customerID)
        {
            ServiceReferenceClient1.GetOrdersFromCustomerRequest inValue = new ServiceReferenceClient1.GetOrdersFromCustomerRequest();
            inValue.Body = new ServiceReferenceClient1.GetOrdersFromCustomerRequestBody();
            inValue.Body.customerID = customerID;
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetOrdersFromCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient1.GetOrderLinesFromOrderResponse ServiceReferenceClient1.WebService1Soap.GetOrderLinesFromOrder(ServiceReferenceClient1.GetOrderLinesFromOrderRequest request)
        {
            return base.Channel.GetOrderLinesFromOrder(request);
        }
        
        public System.Collections.Generic.List<ServiceReferenceClient1.Orderline> GetOrderLinesFromOrder(int OrderID)
        {
            ServiceReferenceClient1.GetOrderLinesFromOrderRequest inValue = new ServiceReferenceClient1.GetOrderLinesFromOrderRequest();
            inValue.Body = new ServiceReferenceClient1.GetOrderLinesFromOrderRequestBody();
            inValue.Body.OrderID = OrderID;
            ServiceReferenceClient1.GetOrderLinesFromOrderResponse retVal = ((ServiceReferenceClient1.WebService1Soap)(this)).GetOrderLinesFromOrder(inValue);
            return retVal.Body.GetOrderLinesFromOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrderLinesFromOrderResponse> ServiceReferenceClient1.WebService1Soap.GetOrderLinesFromOrderAsync(ServiceReferenceClient1.GetOrderLinesFromOrderRequest request)
        {
            return base.Channel.GetOrderLinesFromOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient1.GetOrderLinesFromOrderResponse> GetOrderLinesFromOrderAsync(int OrderID)
        {
            ServiceReferenceClient1.GetOrderLinesFromOrderRequest inValue = new ServiceReferenceClient1.GetOrderLinesFromOrderRequest();
            inValue.Body = new ServiceReferenceClient1.GetOrderLinesFromOrderRequestBody();
            inValue.Body.OrderID = OrderID;
            return ((ServiceReferenceClient1.WebService1Soap)(this)).GetOrderLinesFromOrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/WebServiceClient1/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/WebServiceClient1/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
